services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: social-distro-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - datahub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  # LLM Engine
  ollama:
    image: ollama/ollama:latest
    container_name: social-distro-llm
    ports:
      - "11434:11434"
    volumes:
      - ${HOME}/.ollama:/root/.ollama
    networks:
      - datahub-network
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      retries: 5

  ollama-init:
    image: curlimages/curl:latest
    container_name: social-distro-model-puller
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - datahub-network
    entrypoint: >
      /bin/sh -c "
        echo 'Checking if model exists...';
        if ! curl -s http://ollama:11434/api/tags | grep -q 'phi3:mini'; then
          echo 'Model not found. Pulling phi3:mini...';
          curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"phi3:mini\"}';
        else
          echo 'Model phi3:mini already exists.';
        fi
      "

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.7
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - datahub-network
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.7.7
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - datahub-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "cub", "kafka-ready", "1", "20", "-b", "kafka:29092"]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: social-distro-backend
    ports:
      - "8080:8080"
    networks:
      - datahub-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "false"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      ollama:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  datahub-network: